### ISSUE TITLE
Implement document groups

### ISSUE THREAD

**Issue by RedundantComputation** [Teleoscope/Teleoscope#51]

**Comment by pbucci** [comment]
Building on your work from bookmarking, implement document groups. Ideally, you can start like this:

1. Give each document the ability to be labeled with text tag and/or colour.

This does NOT need to be pretty to start with, just implement it exactly the same as you would with the bookmark except now rather than two states (on/off) it can have have a larger number of states. Ensure that the solution you come up with is visible across the entire workspace, i.e., the text label shows up everywhere. I'd literally just do it so that you click a button until it's the colour/tag you want.

E.g., just say you can be in the Red, Green, or Blue group. Hard code those in. Test rigorously by clicking all over the place. Then move to:

2. Create an editable global list of named groups.

Make an input field which allows you to name new tags. To start, just make sure that you can name new tags and they will be saved to a store. Then make sure you can see all the tags in a dropdown selector.

3. Make it so that selected/highlighted/checkmarked documents (whatever is easiest) are added to the group that is selected in the dropdown selector.

4. Make it so that you can delete and edit tag name in the dropdown selector.
